spring.application.name=ai-chatbot
server.port = 8080

spring.ai.openai.chat.options.model = gpt-5
spring.ai.openai.chat.options.temprature = 1
spring.ai.openai.api-key=sk-proj-vcZXX9_99akaatiZkL431Gq1b4s5kDqEllsXa4IFN